{"id": "graphql.error.located_error", "path": "c:\\Users\\joaoc\\Documents\\GitHub\\graphql-core\\graphql\\error\\located_error.py", "mtime": 1608318730, "size": 1653, "hash": "693fae43f73d2ccc4728997d4f2dc0c1", "data_mtime": 1608568792, "dependencies": ["logging", "sys", "graphql.error.base", "builtins"], "suppressed": [], "child_modules": [], "options": {"warn_unused_ignores": false, "show_none_errors": true, "disallow_untyped_calls": false, "platform": "win32", "warn_no_return": true, "cache_fine_grained": false, "disallow_any_explicit": false, "disallow_any_decorated": false, "disallow_subclassing_any": false, "always_false": [], "quick_and_dirty": false, "follow_imports": "silent", "disallow_any_expr": false, "no_implicit_optional": false, "ignore_errors": false, "strict_optional": false, "follow_imports_for_stubs": false, "strict_optional_whitelist": null, "disallow_any_generics": false, "always_true": [], "disallow_any_unimported": false, "check_untyped_defs": false, "strict_boolean": false, "disallow_untyped_decorators": false, "ignore_missing_imports": true, "warn_return_any": false, "disallow_untyped_defs": false}, "dep_prios": [10, 10, 5, 5], "dep_lines": [1, 2, 4, 1], "interface_hash": "ead5d9bf35d14b8c36bd8c159e712f8e", "version_id": "0.590", "ignore_all": true}
